name: Build EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4  # 更新到v4

    - name: Set up Python
      uses: actions/setup-python@v5  # 更新到v5
      with:
        python-version: '3.11'  # 推荐使用更新的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name MySQLBackupTool main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # 关键修改：更新到v4
      with:
        name: MySQLBackupTool
        path: dist/MySQLBackupTool.exe
